CREATE TABLE departments (department_id SERIAL NOT NULL, department_name CHARACTER VARYING(100) NOT NULL, CONSTRAINT pk_department_id PRIMARY KEY (department_id), CONSTRAINT unique_name UNIQUE (department_name));
CREATE TABLE employees (employee_id SERIAL NOT NULL, last_name CHARACTER VARYING(100) NOT NULL, first_name CHARACTER VARYING(100) NOT NULL, gender CHARACTER VARYING(100), dob DATE NOT NULL, date_of_hire DATE NOT NULL, department_id INTEGER NOT NULL, CONSTRAINT pk_emplyee_id PRIMARY KEY (employee_id), CONSTRAINT fk_employee_department_id FOREIGN KEY (department_id) REFERENCES "departments" ("department_id"));
CREATE TABLE employees_projects (employee_id INTEGER NOT NULL, project_id INTEGER NOT NULL, CONSTRAINT fk_employees_projects_employee_id FOREIGN KEY (employee_id) REFERENCES "employees" ("employee_id"), CONSTRAINT fk_employees_projects_project_id FOREIGN KEY (project_id) REFERENCES "projects" ("project_id"));
CREATE TABLE projects (project_id SERIAL NOT NULL, project_name CHARACTER VARYING(100) NOT NULL, start_date DATE NOT NULL, CONSTRAINT pk_project_id PRIMARY KEY (project_id));

INSERT INTO departments (department_name) VALUES ('MARKETINGa', 'HaR', 'SALEaS', 'PRODUCTaION');
INSERT INTO employees (last_name, first_name, gender, dob, date_of_hire, department_id) VALUES ('MARKEL', 'STEVEN', 'male', '12/12/12', '12/12/12', 21), ('MARKEL', 'KELLY', 'female', '11/11/11', '11/11/11', 22), ('CHEESE', 'BURGER', 'male', '12/12/12', '12/12/12', 23), ('HUNK', 'BUTTER', 'male', '10/12/12', '12/11/12', 24), ('STICK', 'STICK', 'male', '12/12/12', '12/12/12', 21), ('FRANK', 'SLEEP', 'male', '12/12/12', '12/12/12', 22), ('HAPPY', 'SAD', 'female', '12/12/12', '12/12/12', 23), ('MARKEL', 'STEVEN', 'male', '12/12/12', '12/12/12', 24);
INSERT INTO employees_projects (employee_id, project_id) VALUES (25, 9), (25, 10), (26, 11), (27, 11), (27, 10), (26, 9), (28, 10);
INSERT INTO projects (project_name, start_date) VALUES ('Chicken Maker', '11/11/18'), ('Timebomb Of Love', '2/14/28'), ('SBD noise-maker', '1/11/11');
